### ISSUE TITLE
add an option `showCurrentYear` to make year optional

### ISSUE THREAD

**Issue by creharmony** [saurav90/react-simple-timestamp-to-date#3]
I would like an extra option (ex. `showCurrentYear`, default to `1 `)

- when set to `1`, there is no difference from current behavior.
- when set to `0`,component will displays the year (from format) if and only if she is different from current year.

For example:
```
<SimpleDateTime dateFormat="DMY" dateSeparator="/" showTime="0">{myTimestamp}</SimpleDateTime>
```

will render as `23/11/2021`

whereas (assume 2021 is current year)
```
<SimpleDateTime dateFormat="DMY" dateSeparator="/" showTime="0" showCurrentYear="0">{myTimestamp}</SimpleDateTime>
```

will render as `23/11`

**Comment by creharmony** [comment]
I've done it using dayjs

````
function tsToDateMonthYear(dateTs) {
  const tsDayJs = dayjs.unix(dateTs);
  if (tsDayJs > dayjs().startOf('year') && tsDayJs < dayjs().endOf('year')) {
    return dayjs.unix(dateTs).format('DD/MM');
  }
  return dayjs.unix(dateTs).format('DD/MM/YYYY');
}
````

**Comment by saurav90** [comment]
> I've done it using dayjs
> 
> ```
> function tsToDateMonthYear(dateTs) {
>   const tsDayJs = dayjs.unix(dateTs);
>   if (tsDayJs > dayjs().startOf('year') && tsDayJs < dayjs().endOf('year')) {
>     return dayjs.unix(dateTs).format('DD/MM');
>   }
>   return dayjs.unix(dateTs).format('DD/MM/YYYY');
> }
> ```

Sorry for being Ghosted from this repo, I have just added another few formats, "DM, MD, MY, D, M, Y" which may solve your problem and others in near future.
